import api from "./api";
export const register = (data) => api.post("/auth/register", data);
export const verifyOtp = (data) => api.post("/auth/verify-otp", data);
export const resendOtp = (data) => api.post("/auth/resend-otp", data);
export const login = (data) => api.post("/auth/login", data);
export const getMe = () => api.get("/auth/me");
export const forgotPassword = (data) => api.post("/auth/forgot-password", data);
export const verifyResetOtp = (data) => api.post("/auth/verify-reset-otp", data);
export const resetPassword = (data) => api.post("/auth/reset-password", data);
export const getStats = () => api.get("/auth/me/stats");
export const updateProfile = (data) => api.put("/users/me", data);
export const deleteAccount = () => api.delete("/users/me");
