"""Baseline migration

Revision ID: 76f7610086e6
Revises: 
Create Date: 2026-09-28 22:54:13.839739

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '76f7610086e6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('comments', 'is_pinned',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.drop_index(op.f('idx_comments_post'), table_name='comments')
    op.create_index(op.f('ix_comments_created_at'), 'comments', ['created_at'], unique=False)
    op.create_index(op.f('ix_comments_post_id'), 'comments', ['post_id'], unique=False)
    op.drop_constraint(op.f('conversation_read_receipts_conversation_id_user_id_key'), 'conversation_read_receipts', type_='unique')
    op.create_unique_constraint('uq_read_receipt', 'conversation_read_receipts', ['conversation_id', 'user_id'])
    op.drop_index(op.f('idx_friend_req_receiver'), table_name='friend_requests')
    op.alter_column('messages', 'content',
               existing_type=sa.TEXT(),
               type_=sa.String(length=4000),
               existing_nullable=False)
    op.drop_index(op.f('idx_messages_conversation'), table_name='messages')
    op.create_index(op.f('ix_messages_conversation_id'), 'messages', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_messages_sent_at'), 'messages', ['sent_at'], unique=False)
    op.drop_constraint(op.f('post_likes_post_id_user_id_key'), 'post_likes', type_='unique')
    op.create_unique_constraint('uq_post_like', 'post_likes', ['post_id', 'user_id'])
    op.drop_index(op.f('idx_posts_author_status'), table_name='posts')
    op.create_index(op.f('ix_posts_author_id'), 'posts', ['author_id'], unique=False)
    op.create_index(op.f('ix_posts_created_at'), 'posts', ['created_at'], unique=False)
    op.drop_constraint(op.f('saved_posts_post_id_user_id_key'), 'saved_posts', type_='unique')
    op.create_unique_constraint('uq_saved_post', 'saved_posts', ['post_id', 'user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_saved_post', 'saved_posts', type_='unique')
    op.create_unique_constraint(op.f('saved_posts_post_id_user_id_key'), 'saved_posts', ['post_id', 'user_id'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_posts_created_at'), table_name='posts')
    op.drop_index(op.f('ix_posts_author_id'), table_name='posts')
    op.create_index(op.f('idx_posts_author_status'), 'posts', ['author_id', 'status'], unique=False)
    op.drop_constraint('uq_post_like', 'post_likes', type_='unique')
    op.create_unique_constraint(op.f('post_likes_post_id_user_id_key'), 'post_likes', ['post_id', 'user_id'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_messages_sent_at'), table_name='messages')
    op.drop_index(op.f('ix_messages_conversation_id'), table_name='messages')
    op.create_index(op.f('idx_messages_conversation'), 'messages', ['conversation_id', 'sent_at'], unique=False)
    op.alter_column('messages', 'content',
               existing_type=sa.String(length=4000),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.create_index(op.f('idx_friend_req_receiver'), 'friend_requests', ['receiver_id', 'status'], unique=False)
    op.drop_constraint('uq_read_receipt', 'conversation_read_receipts', type_='unique')
    op.create_unique_constraint(op.f('conversation_read_receipts_conversation_id_user_id_key'), 'conversation_read_receipts', ['conversation_id', 'user_id'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_comments_post_id'), table_name='comments')
    op.drop_index(op.f('ix_comments_created_at'), table_name='comments')
    op.create_index(op.f('idx_comments_post'), 'comments', ['post_id'], unique=False)
    op.alter_column('comments', 'is_pinned',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    # ### end Alembic commands ###
