"""Add composite indexes for messages

Revision ID: 9ef731df7de2
Revises: 76f7610086e6
Create Date: 2026-09-28 22:58:35.263244

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ef731df7de2'
down_revision: Union[str, Sequence[str], None] = '76f7610086e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_messages_conversation_sent_at', 'messages', ['conversation_id', 'sent_at'], unique=False)
    op.create_index('ix_messages_group_sent_at', 'messages', ['group_id', 'sent_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_messages_group_sent_at', table_name='messages')
    op.drop_index('ix_messages_conversation_sent_at', table_name='messages')
    # ### end Alembic commands ###
