"""Add composite indexes for blog

Revision ID: cf725b0a5827
Revises: 9ef731df7de2
Create Date: 2026-09-28 22:59:57.803261

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cf725b0a5827'
down_revision: Union[str, Sequence[str], None] = '9ef731df7de2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_comments_post_pinned_created_at', 'comments', ['post_id', 'is_pinned', 'created_at'], unique=False)
    op.create_index('ix_posts_author_created_at', 'posts', ['author_id', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_posts_author_created_at', table_name='posts')
    op.drop_index('ix_comments_post_pinned_created_at', table_name='comments')
    # ### end Alembic commands ###
